export let data = {
    FirstName: "FIRSTNAME",
    SecondName: "SECONDNAME",
    PhoneNumber: '999999xxxxx',
    Place: "City, State",
    Mail: "abc@mail.com",
    College: "CollegeName",
    CollegePlace: "City, State",
    Degree: "Degree",
    Branch: "Branch",
    duration: "Start-End",
    GPA: "Obtained/total",
    Project1Name: "Project 1",
    Project1Point1: " sample point one",
    Project1Point2: " sample point two",
    Project2Name: "Project 2",
    Project2Point1: " sample point one",
    Project2Point2: " sample point two",
    Technical: "",
    Soft: "",
    Language: "",
    Other: "",
    Company: "Company Name",
    Role: "Position/Role",
    CompanyPoint1: "About your work in company",
    CompanyPoint2: "About your work in company",
    CompanyDuration: "Start-End",
    img: ""
}